### ISSUE TITLE
Is actualvim being developed?

### ISSUE THREAD

**Issue by jordwalke** [lunixbochs/actualvim#31]
Hi, I think this approach to a Vim mode is excellent. I'm curious if anyone is currently developing and refining actualvim. I understand if not - things come up. I'm just curious.

**Comment by jordwalke** [comment]
That's too bad. I think this project has the right approach and I'd love to see it get some attention (even if from someone else). Thanks for showing that this can be done.

**Comment by lunixbochs** [comment]
Neovim has since matured, and I'm in the middle of porting this to it. Actualvim is a great starting point for the Sublime integration, and Neovim provides everything I need to do a seamless integration. Maybe look for it in a couple of months, or if I get some free time away from my many other projects.

**Comment by jordwalke** [comment]
That sounds great.

**Comment by jordwalke** [comment]
Are you thinking about picking up development of this again?

**Comment by lunixbochs** [comment]
Good news is coming: https://github.com/lunixbochs/actualvim/tree/neovim

**Comment by lunixbochs** [comment]
closing as fixed, see #38
