### ISSUE TITLE
Cursor positioning when searching does not work with multibyte text

### ISSUE THREAD

**Issue by svenax** [lunixbochs/actualvim#51]
When positioning the cursor at a search result in multibyte text, `actualvim` counts bytes instead of characters in the lines, putting the cursor at the wrong position.

**Comment by lunixbochs** [comment]
There's a similar problem if Sublime converts your tabs to spaces but Vim doesn't.

**Comment by svenax** [comment]
So the character encoding and tab setting (and maybe more; e.g. line endings?) nedds to be synced from Sublime to Neovim. Shouldn't be too hard I think.

**Comment by lunixbochs** [comment]
This is a fairly high priority because it makes autoindent while programming feel pretty awkward.

vim uses byte offsets instead of character offsets, so I can utf-8 decode/encode the current line to make a better guess

As for tabs, I'm not sure I can think of a better option than forcing sublime's tab settings on vim (or vice versa), and I'm sure different users will have different opinions about this. Maybe an ActualVim setting as to which editor gets tab setting priority?

**Comment by lunixbochs** [comment]
Can you try again on latest master? c82e16c and 9a8e7aa should fix both of these.

**Comment by lunixbochs** [comment]
This should be completely fixed, can you try again?

**Comment by lunixbochs** [comment]
All of my multibyte tests are checking out, closing this.
